[package]
name = "solen"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "migration"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = "0.4.42"
chrono-tz = "0.10.4"
dotenvy = "0.15.0"
html2md = "0.2.15"
migration = { path = "migration" }
poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next" }
rand = "0.10"
regex = "1.13"
reqwest = "0.13"
rss = "2.1"
sea-orm = { version = "2.0.0-rc", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
tokio = { version = "1.53", features = ["macros", "rt-multi-thread"] }
tokio-cron-scheduler = "0.15.1"
url = "2.5.8"
serde = "1.0"
serde_json = "1.0"
bytes = "1.12"
aws-config = "1.10"
aws-sdk-s3 = "1.132.0"
config = "0.15.25"
rustls = "0.23.43"
