[package]
name = "solen"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "migration"]

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1"
chrono = "0.4.42"
chrono-tz = "0.10.4"
dotenv = "0.15.0"
html2md = "0.2.15"
migration = { path = "migration" }
poise = "0.6.2"
rand = "0.10"
regex = "1.12"
reqwest = "0.13"
rss = "2.0.12"
sea-orm = { version = "2.0.0-rc", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
serenity = "0.12.5"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
tokio-cron-scheduler = "0.15.1"
url = "2.5.8"
ollama-rs = { version = "0.3.5", features = ["macros"] }
schemars = "1.2.1"
serde = "1.0.228"
serde_json = "1.0.150"
